# Generated by Django 5.0.6 on 2024-06-14 01:21

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Выберите страну', max_length=2, null=True, verbose_name='Страна'),
        ),
    ]
