# Generated by Django 5.0.4 on 2024-05-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(help_text='Введите описание категории', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название товара', max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(help_text='Введите описание товара', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение продукта', null=True, upload_to='product/image', verbose_name='Изображение')),
                ('price', models.IntegerField(help_text='Введите цену товара', verbose_name='Цена')),
                ('created_at', models.DateField(help_text='Введите дату записи в БД', verbose_name='Дата создания')),
                ('updated_at', models.DateField(help_text='Введите дату последнего изменения', verbose_name='Дата изменения')),
                ('category', models.ForeignKey(help_text='Введите номер категории', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Номер категории')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name', 'category', 'price', 'created_at', 'updated_at'],
            },
        ),
    ]
