# Generated by Django 5.0.6 on 2024-05-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение продукта', null=True, upload_to='category/images', verbose_name='Изображение'),
        ),
    ]
